name: Playwright Tests
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENCE"
      - "CODEOWNERS"
      - ".gitignore"
      - ".github/workflows/build-pr.yaml"
      - ".github/workflows/chainguard-digestabot.yaml"
      - ".github/workflows/codeql-trivy-scan.yaml"
      - ".github/workflows/dependabot-automerge.yaml"
      - ".github/workflows/deploy.yaml"
      - ".github/workflows/manual-deploy.yaml"
      - ".github/dependabot.yaml"

jobs:
  playwright-test:
    permissions:
      contents: read
    name: Playwright test
    uses: navikt/mob-gha-workflows/.github/workflows/playwright.yaml@main
    secrets: inherit
